theme: jekyll-theme-cayman
title: Infoseeker's Website
description: 广阔天地，大有作为
navigation:
  name_over_title: true
  strip_par: true
  sanitize: true
  h_max: 3
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge
